### ISSUE TITLE
Teensy version

### ISSUE THREAD

**Issue by ghost** [srperry96/teensy_drum_pad#1]
Which teensy board did you use? 
Any chance of adding the step sequencer

**Comment by srperry96** [comment]
Teensy 3.2 I believe. Although Teensy 4.0 would work as well - just have to make sure to get the correct Teensy Audio Board to go with it. I haven't found the time to continue work on this project (step sequencer, looper functionalities etc).

**Comment by ghost** [comment]
No worries I'm just experimenting, got it running on teensy 4.0, thanks for sharing it
